config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'courses/', to: 'courses#index'
  get 'products/', to: 'products#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @nombre = "Diego"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end

  def new
    @users = User.new
  end

  def create
    @users = User.new(user_params)
    if @users.save
      redirect_to user_path(@users)
    else
      @errors = @users.errors.full_messages
      render 'users/new'
    end
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<div class="col-lg-8 mb-3"><h1>Courses</h1></div>

<table class="table table-bordered border-primary">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">NAME</th>
    <th scope="col">Descripción</th>
    <th scope="col">Precio</th>
  </tr>
  </thead>
  <tbody>
  <% @courses.each do |product| %>
    <tr>
      <th scope="row"> <%= "#{product.id} "%></th>
      <td><%= "#{product.name} "%></td>
      <td><%= "#{product.description} "%></td>
      <td><%= " $ #{product.price} "%></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Courses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="col-lg-8 mb-3"><h1>Products</h1></div>

<table class="table table-bordered border-primary">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">NAME</th>
    <th scope="col">Descripción</th>
    <th scope="col">Precio</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
  <tr>
    <th scope="row"> <%= "#{product.id} "%></th>
    <td><%= "#{product.name} "%></td>
    <td><%= "#{product.description} "%></td>
    <td><%= " $ #{product.price} "%></td>
  </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

<%= link_to "Crear usuario", new_user_path %>
<br>
<%= link_to "Lista de Productos", courses_path %>
<br>
<%= link_to "Lista de Productos", products_path %>

app/views/users/new.html.erb
<h1> Creando un User</h1>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

<%= form_for @users do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @users.name %></h1>